### ISSUE TITLE
Property Editor: data corruption

### ISSUE THREAD

**Issue by RachelBlueArt** [ashblue/sprite-animator#1]
when editing the position on a layer/frame there is corrupted data. I had to be on at least the second frame, (both in the timeline and on the sprite sheet), then when I went to change the x or y position (by clicking and dragging to highlight the numbers) the numbers were replaced with NaN. The position box then disappeared and all following frames became corrupted as well. This error has not occurred on the first frame, only the second. 

After this happens clicking on the image then causes the position editor to disappear (as seen in capture 3)

![capture1](https://cloud.githubusercontent.com/assets/3829856/3323542/c8b139c4-f764-11e3-93f2-55fe534bf183.PNG)
![capture2](https://cloud.githubusercontent.com/assets/3829856/3323544/cb2f457e-f764-11e3-918f-763dafafa50e.PNG)
![capture3](https://cloud.githubusercontent.com/assets/3829856/3323547/e173da52-f764-11e3-919e-958cad3afaa7.PNG)

**Comment by ashblue** [comment]
Fixed, issue is caused by DAT GUI and had to wrap their API with a NaN error check. Has to do with parsing negative numbers with a certain algorithm.
